Traceback (most recent call last):
  File "C:\Users\Luiz Lima\Documents\GitHub\automatetheboringstuff\Chapter_10\errorExample.py", line 9, in <module>
    spam()
  File "C:\Users\Luiz Lima\Documents\GitHub\automatetheboringstuff\Chapter_10\errorExample.py", line 4, in spam
    bacon()
  File "C:\Users\Luiz Lima\Documents\GitHub\automatetheboringstuff\Chapter_10\errorExample.py", line 6, in bacon
    raise Exception('This is the error message.')
Exception: This is the error message.
